version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "gradle-wrapper"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        update-types: ["version-update:semver-major"]
    groups:
      gradle:
        patterns:
          - "*"
