#ifndef _OPCODES_H_
#define _OPCODES_H_

// Opcode masks
#define OPCODE_MASK_SECOND 0x80

// Arithmetic opcodes
#define OPCODE_MATRIX_IDENTITY 0x01
#define OPCODE_MATRIX_MUL_MATRIX 0x02
#define OPCODE_MATRIX_TRANSPOSE 0x03
#define OPCODE_MATRIX_ROTATEX 0x04
#define OPCODE_MATRIX_ROTATEY 0x05
#define OPCODE_MATRIX_ROTATEZ 0x06
#define OPCODE_MATRIX_TRANSLATE 0x07
#define OPCODE_MATRIX_SCALE 0x08
#define OPCODE_MATRIX_INVERT 0x09
#define OPCODE_MATRIX_TRANSFORM_VECTOR 0x0A
#define OPCODE_MATRIX_ROTATE_QUATERNION 0x0B
#define OPCODE_MATRIX_TRANSLATION_ROTATE_SCALE 0x0C
#define OPCODE_VECTOR_NEGATE 0x0D

// Memory management opcodes
#define OPCODE_STORE 0x40
#define OPCODE_LOAD 0x41
#define OPCODE_EXCHANGE 0x42
#define OPCODE_COPY 0x43
#define OPCODE_COPY_MEM 0x44

#endif
