#ifndef _OPCODES_H_
#define _OPCODES_H_

#define OPCODE_MATRIX_MUL_MATRIX 0x01
#define OPCODE_MATRIX_TRANSPOSE 0x03
#define OPCODE_ROTATEZ 0x06
#define OPCODE_MATRIX_GET 0x09
#define OPCODE_MATRIX_IDENTITY 0x0A
#define OPCODE_ROTATEX 0x0B
#define OPCODE_ROTATEY 0x0C
#define OPCODE_MATRIX_SCALE 0x0D
#define OPCODE_MATRIX_TRANSLATE 0x0E

#endif
